export const textCategories = {
  short: {
    shakespeare: [
      "To be, or not to be, that is the question. Whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles. The heartache and the thousand natural shocks that flesh is heir to must give us pause.",
      "All the world's a stage, and all the men and women merely players. They have their exits and their entrances, and one man in his time plays many parts. His acts being seven ages, from the infant to the old man.",
      "The quality of mercy is not strained. It droppeth as the gentle rain from heaven upon the place beneath. It is twice blest: it blesseth him that gives and him that takes.",
      "Friends, Romans, countrymen, lend me your ears. I come to bury Caesar, not to praise him. The evil that men do lives after them; the good is oft interred with their bones.",
      "But soft! What light through yonder window breaks? It is the east, and Juliet is the sun. Arise, fair sun, and kill the envious moon, who is already sick and pale with grief."
    ],
    anime: [
      "I'm going to be the King of the Pirates! I don't want to conquer anything. I just think the guy with the most freedom in the whole ocean is the Pirate King!",
      "The One Piece is real! I don't care who you are! I don't care if you're a god! If you hurt my friends, I'll make you pay!",
      "I don't want to be a hero. Heroes have to share their meat. I want all the meat! When you're at sea, you fight against the sea!",
      "A man's dream will never die! I want to live! Take me out to sea with you! The world isn't perfect, but it's there for us.",
      "When you're at sea, you fight against the sea! When you're on land, you fight against the pirates! When you're hungry, you fight against the hunger!"
    ],
    aesop: [
      "A fox, walking through the forest, saw a bunch of grapes hanging from a high branch. 'Just the thing to quench my thirst,' he thought. Taking a few steps back, the fox jumped and just missed the hanging grapes.",
      "A crow was sitting on a tree, doing nothing all day. A small rabbit saw the crow, and asked him, 'Can I also sit like you and do nothing all day long?' The crow answered: 'Sure, why not.'",
      "A man and his son were once going with their donkey to market. As they were walking along by its side a countryman passed them and said: 'You fools, what is a donkey for but to ride upon?'",
      "A wolf was prowling around a flock of sheep when he came across a sheepskin that had been cast aside and forgotten. The next day, dressed in the skin, the wolf strolled into the pasture with the flock.",
      "A farmer had some puppies he needed to sell. He painted a sign advertising the pups and set about nailing it to a post on the edge of his yard. As he was driving the last nail into the post, he felt a tug on his overalls."
    ]
  },
  medium: {
    shakespeare: [
      "To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles and by opposing end them. To die, to sleep—no more—and by a sleep to say we end the heartache and the thousand natural shocks that flesh is heir to.",
      "All the world's a stage, and all the men and women merely players. They have their exits and their entrances, and one man in his time plays many parts, his acts being seven ages. At first, the infant, mewling and puking in the nurse's arms. Then the whining schoolboy, with his satchel and shining morning face, creeping like snail unwillingly to school.",
      "The quality of mercy is not strained. It droppeth as the gentle rain from heaven upon the place beneath. It is twice blest: It blesseth him that gives and him that takes. 'Tis mightiest in the mightiest. It becomes the throned monarch better than his crown. His scepter shows the force of temporal power, the attribute to awe and majesty.",
      "Friends, Romans, countrymen, lend me your ears. I come to bury Caesar, not to praise him. The evil that men do lives after them; the good is oft interred with their bones. So let it be with Caesar. The noble Brutus hath told you Caesar was ambitious. If it were so, it was a grievous fault, and grievously hath Caesar answered it.",
      "But soft! What light through yonder window breaks? It is the east, and Juliet is the sun. Arise, fair sun, and kill the envious moon, who is already sick and pale with grief that thou, her maid, art far more fair than she. Be not her maid, since she is envious. Her vestal livery is but sick and green, and none but fools do wear it."
    ],
    anime: [
      "I don't want to conquer anything. I just think the guy with the most freedom in the whole ocean is the Pirate King! That's all! I don't want to be a hero. Heroes have to share their meat. I want all the meat! When you're at sea, you fight against the sea! When you're on land, you fight against the pirates! When you're hungry, you fight against the hunger!",
      "The world isn't perfect. But it's there for us, doing the best it can. That's what makes it so damn beautiful. If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. When you aim high, you sometimes come across fights not worth fighting. And sometimes, life teaches you a lesson you never forget.",
      "I'm not a hero. I'm a pirate. Heroes share their meat. Pirates keep their meat to themselves! When you aim high, you sometimes come across fights not worth fighting. And sometimes, life teaches you a lesson you never forget. When that happens, it's not enough to say you're sorry. Being strong isn't just about having power or weapons.",
      "The One Piece is real! I don't care who you are! I don't care if you're a god! If you hurt my friends, I'll make you pay! When you're at sea, you fight against the sea! When you're on land, you fight against the pirates! When you're hungry, you fight against the hunger! When you're on an adventure, you fight against the adventure!",
      "A man's dream will never die! I want to live! Take me out to sea with you! When you're at sea, you fight against the sea! When you're on land, you fight against the pirates! When you're hungry, you fight against the hunger! When you're on an adventure, you fight against the adventure! That's what it means to be alive!"
    ],
    aesop: [
      "A crow was sitting on a tree, doing nothing all day. A small rabbit saw the crow, and asked him, 'Can I also sit like you and do nothing all day long?' The crow answered: 'Sure, why not.' So, the rabbit sat on the ground below the crow, and rested. All of a sudden, a fox appeared, jumped on the rabbit and ate it. Moral of the story: To be sitting and doing nothing, you must be sitting very, very high up.",
      "A farmer had some puppies he needed to sell. He painted a sign advertising the pups and set about nailing it to a post on the edge of his yard. As he was driving the last nail into the post, he felt a tug on his overalls. He looked down into the eyes of a little boy. 'Mister,' he said, 'I want to buy one of your puppies.' The farmer knelt down at the boy's side and said, 'Son, you don't want that puppy. He will never be able to run and play with you like these other dogs would.'",
      "A man and his son were once going with their donkey to market. As they were walking along by its side a countryman passed them and said: 'You fools, what is a donkey for but to ride upon?' So the man put the boy on the donkey, and they went on their way. But soon they passed a group of men, one of whom said: 'See that lazy youngster, he lets his father walk while he rides.' So the man ordered his boy to get off, and got on himself.",
      "A fox was walking through the forest when he saw a crow sitting on a tree branch with a piece of cheese in her beak. The fox wanted the cheese for himself, so he called up to the crow, 'Good day, Mistress Crow! How well you are looking today! How glossy your feathers! How bright your eyes! I feel sure your voice must surpass that of other birds, just as your figure does. Let me hear but one song from you that I may greet you as the Queen of Birds.'",
      "A lion was awakened from sleep by a mouse running over his face. Rising up angrily, he caught him and was about to kill him, when the mouse piteously entreated, saying: 'If you would only spare my life, I would be sure to repay your kindness.' The lion laughed and let him go. It happened shortly after this that the lion was caught by some hunters, who bound him by strong ropes to the ground. The mouse, recognizing his roar, came and gnawed the rope with his teeth and set him free, exclaiming: 'You ridiculed the idea of my ever being able to help you, not expecting to receive from me any repayment of your favor.'"
    ]
  },
  long: {
    shakespeare: [
      "To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer the slings and arrows of outrageous fortune, or to take arms against a sea of troubles and by opposing end them. To die, to sleep—no more—and by a sleep to say we end the heartache and the thousand natural shocks that flesh is heir to—'tis a consummation devoutly to be wished! To die, to sleep. To sleep, perchance to dream—ay, there's the rub, for in that sleep of death what dreams may come when we have shuffled off this mortal coil must give us pause. There's the respect that makes calamity of so long life. For who would bear the whips and scorns of time, the oppressor's wrong, the proud man's contumely, the pangs of despised love, the law's delay, the insolence of office, and the spurns that patient merit of the unworthy takes, when he himself might his quietus make with a bare bodkin?",
      "All the world's a stage, and all the men and women merely players. They have their exits and their entrances, and one man in his time plays many parts, his acts being seven ages. At first, the infant, mewling and puking in the nurse's arms. Then the whining schoolboy, with his satchel and shining morning face, creeping like snail unwillingly to school. And then the lover, sighing like furnace, with a woeful ballad made to his mistress' eyebrow. Then a soldier, full of strange oaths and bearded like the pard, jealous in honor, sudden and quick in quarrel, seeking the bubble reputation even in the cannon's mouth. And then the justice, in fair round belly with good capon lined, with eyes severe and beard of formal cut, full of wise saws and modern instances.",
      "The quality of mercy is not strained. It droppeth as the gentle rain from heaven upon the place beneath. It is twice blest: It blesseth him that gives and him that takes. 'Tis mightiest in the mightiest. It becomes the throned monarch better than his crown. His scepter shows the force of temporal power, the attribute to awe and majesty, wherein doth sit the dread and fear of kings. But mercy is above this sceptered sway. It is enthroned in the hearts of kings. It is an attribute to God himself. And earthly power doth then show likest God's when mercy seasons justice. Therefore, Jew, though justice be thy plea, consider this: that in the course of justice none of us should see salvation. We do pray for mercy, and that same prayer doth teach us all to render the deeds of mercy.",
      "Friends, Romans, countrymen, lend me your ears. I come to bury Caesar, not to praise him. The evil that men do lives after them; the good is oft interred with their bones. So let it be with Caesar. The noble Brutus hath told you Caesar was ambitious. If it were so, it was a grievous fault, and grievously hath Caesar answered it. Here, under leave of Brutus and the rest—for Brutus is an honorable man; so are they all, all honorable men—come I to speak in Caesar's funeral. He was my friend, faithful and just to me. But Brutus says he was ambitious, and Brutus is an honorable man. He hath brought many captives home to Rome, whose ransoms did the general coffers fill. Did this in Caesar seem ambitious? When that the poor have cried, Caesar hath wept. Ambition should be made of sterner stuff.",
      "But soft! What light through yonder window breaks? It is the east, and Juliet is the sun. Arise, fair sun, and kill the envious moon, who is already sick and pale with grief that thou, her maid, art far more fair than she. Be not her maid, since she is envious. Her vestal livery is but sick and green, and none but fools do wear it. Cast it off. It is my lady. O, it is my love! O, that she knew she were! She speaks, yet she says nothing. What of that? Her eye discourses. I will answer it. I am too bold. 'Tis not to me she speaks. Two of the fairest stars in all the heaven, having some business, do entreat her eyes to twinkle in their spheres till they return. What if her eyes were there, they in her head? The brightness of her cheek would shame those stars as daylight doth a lamp. Her eyes in heaven would through the airy region stream so bright that birds would sing and think it were not night."
    ],
    anime: [
      "I don't want to conquer anything. I just think the guy with the most freedom in the whole ocean is the Pirate King! That's all! I don't want to be a hero. Heroes have to share their meat. I want all the meat! When you're at sea, you fight against the sea! When you're on land, you fight against the pirates! When you're hungry, you fight against the hunger! When you're on an adventure, you fight against the adventure! That's what it means to be alive! The world isn't perfect. But it's there for us, doing the best it can. That's what makes it so damn beautiful. If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. When you aim high, you sometimes come across fights not worth fighting. And sometimes, life teaches you a lesson you never forget. When that happens, it's not enough to say you're sorry. Being strong isn't just about having power or weapons, it's about having the heart to accept your enemy's pain and understand it.",
      "The One Piece is real! I don't care who you are! I don't care if you're a god! If you hurt my friends, I'll make you pay! When you're at sea, you fight against the sea! When you're on land, you fight against the pirates! When you're hungry, you fight against the hunger! When you're on an adventure, you fight against the adventure! That's what it means to be alive! The world isn't perfect. But it's there for us, doing the best it can. That's what makes it so damn beautiful. If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. When you aim high, you sometimes come across fights not worth fighting. And sometimes, life teaches you a lesson you never forget. When that happens, it's not enough to say you're sorry. Being strong isn't just about having power or weapons, it's about having the heart to accept your enemy's pain and understand it.",
      "I'm not a hero. I'm a pirate. Heroes share their meat. Pirates keep their meat to themselves! When you aim high, you sometimes come across fights not worth fighting. And sometimes, life teaches you a lesson you never forget. When that happens, it's not enough to say you're sorry. Being strong isn't just about having power or weapons, it's about having the heart to accept your enemy's pain and understand it. The world isn't perfect. But it's there for us, doing the best it can. That's what makes it so damn beautiful. If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. When you're at sea, you fight against the sea! When you're on land, you fight against the pirates! When you're hungry, you fight against the hunger! When you're on an adventure, you fight against the adventure! That's what it means to be alive!",
      "A man's dream will never die! I want to live! Take me out to sea with you! When you're at sea, you fight against the sea! When you're on land, you fight against the pirates! When you're hungry, you fight against the hunger! When you're on an adventure, you fight against the adventure! That's what it means to be alive! The world isn't perfect. But it's there for us, doing the best it can. That's what makes it so damn beautiful. If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. When you aim high, you sometimes come across fights not worth fighting. And sometimes, life teaches you a lesson you never forget. When that happens, it's not enough to say you're sorry. Being strong isn't just about having power or weapons, it's about having the heart to accept your enemy's pain and understand it.",
      "I'm going to be the King of the Pirates! I don't want to conquer anything. I just think the guy with the most freedom in the whole ocean is the Pirate King! That's all! I don't want to be a hero. Heroes have to share their meat. I want all the meat! When you're at sea, you fight against the sea! When you're on land, you fight against the pirates! When you're hungry, you fight against the hunger! When you're on an adventure, you fight against the adventure! That's what it means to be alive! The world isn't perfect. But it's there for us, doing the best it can. That's what makes it so damn beautiful. If you don't like your destiny, don't accept it. Instead, have the courage to change it the way you want it to be. When you aim high, you sometimes come across fights not worth fighting. And sometimes, life teaches you a lesson you never forget. When that happens, it's not enough to say you're sorry. Being strong isn't just about having power or weapons, it's about having the heart to accept your enemy's pain and understand it."
    ],
    aesop: [
      "A farmer had some puppies he needed to sell. He painted a sign advertising the pups and set about nailing it to a post on the edge of his yard. As he was driving the last nail into the post, he felt a tug on his overalls. He looked down into the eyes of a little boy. 'Mister,' he said, 'I want to buy one of your puppies.' 'Well,' said the farmer, as he rubbed the sweat off the back of his neck, 'these puppies come from fine parents and cost a good deal of money.' The boy dropped his head for a moment. Then reaching deep into his pocket, he pulled out a handful of change and held it up to the farmer. 'I've got thirty-nine cents. Is that enough to take a look?' 'Sure,' said the farmer. And with that he let out a whistle. 'Here, Dolly!' he called. Out from the doghouse and down the ramp ran Dolly followed by four little balls of fur. The little boy pressed his face against the chain link fence. His eyes danced with delight. As the dogs made their way to the fence, the little boy noticed something else stirring inside the doghouse. Slowly another little ball appeared, this one noticeably smaller. Down the ramp it slid. Then in a somewhat awkward manner, the little pup began hobbling toward the others, doing its best to catch up. 'I want that one,' the little boy said, pointing to the runt. The farmer knelt down at the boy's side and said, 'Son, you don't want that puppy. He will never be able to run and play with you like these other dogs would.' With that the little boy stepped back from the fence, reached down, and began rolling up one leg of his trousers. In doing so he revealed a steel brace running down both sides of his leg attaching itself to a specially made shoe. Looking back up at the farmer, he said, 'You see sir, I don't run too well myself, and he will need someone who understands.'",
      "A crow was sitting on a tree, doing nothing all day. A small rabbit saw the crow, and asked him, 'Can I also sit like you and do nothing all day long?' The crow answered: 'Sure, why not.' So, the rabbit sat on the ground below the crow, and rested. All of a sudden, a fox appeared, jumped on the rabbit and ate it. Moral of the story: To be sitting and doing nothing, you must be sitting very, very high up. The crow was safe because he was sitting high up in the tree, while the rabbit was vulnerable on the ground. This story teaches us that sometimes it's better to be in a position of safety before we decide to relax and do nothing. It also reminds us that we should always be aware of our surroundings and potential dangers, even when we think we're safe. The rabbit learned this lesson the hard way, but we can learn from his mistake without having to experience it ourselves.",
      "A man and his son were once going with their donkey to market. As they were walking along by its side a countryman passed them and said: 'You fools, what is a donkey for but to ride upon?' So the man put the boy on the donkey, and they went on their way. But soon they passed a group of men, one of whom said: 'See that lazy youngster, he lets his father walk while he rides.' So the man ordered his boy to get off, and got on himself. But they hadn't gone far when they passed two women, one of whom said to the other: 'Shame on that lazy lout to let his poor little son trudge along.' Well, the man didn't know what to do, but at last he took his boy up before him on the donkey. By this time they had come to the town, and the passers-by began to jeer and point at them. The man stopped and asked what they were scoffing at. The men said: 'Aren't you ashamed of yourself for overloading that poor donkey of yours—you and your hulking son?' The man and boy got off and tried to think what to do. They thought and they thought, till at last they cut down a pole, tied the donkey's feet to it, and raised the pole and the donkey to their shoulders. They went along amid the laughter of all who met them till they came to Market Bridge, when the donkey, getting one of his feet loose, kicked out and caused the boy to drop his end of the pole. In the struggle the donkey fell over the bridge, and his forefeet being tied together he was drowned. 'That will teach you,' said an old man who had followed them: 'Please all, and you will please none.'"
    ]
  }
};

export const timeModes = {
  words: "Complete the text",
  "30s": "30 seconds",
  "60s": "60 seconds",
  "90s": "90 seconds"
}; 