export const textCategories = {
  short: {
    shakespeare: [
      "To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take Arms against a Sea of troubles, And by opposing end them: to die, to sleep No more; and by a sleep, to say we end The heart-ache, and the thousand natural shocks That Flesh is heir to? 'Tis a consummation Devoutly to be wished. To die, to sleep, To sleep, perchance to Dream; aye, there's the rub, For in that sleep of death, what dreams may come, When we have shuffled off this mortal coil, Must give us pause.",
      "All the world's a stage, And all the men and women merely players; They have their exits and their entrances; And one man in his time plays many parts, His acts being seven ages. At first, the infant, Mewling and puking in the nurse's arms. Then the whining schoolboy, with his satchel And shining morning face, creeping like snail Unwillingly to school. And then the lover, Sighing like furnace, with a woeful ballad Made to his mistress' eyebrow.",
      "The course of true love never did run smooth. But, either it was different in blood, Or else misgraffed in respect of years, Or else it stood upon the choice of friends, Or, if there were a sympathy in choice, War, death, or sickness did lay siege to it, Making it momentany as a sound, Swift as a shadow, short as any dream, Brief as the lightning in the collied night, That, in a spleen, unfolds both heaven and earth, And ere a man hath power to say 'Behold!' The jaws of darkness do devour it up: So quick bright things come to confusion."
    ],
    anime: [
      "I am going to be the Hokage! No one will ever stop me! Even if I have to die, I'll never give up! I'll become the greatest ninja ever, and everyone will acknowledge my existence! That's my dream, that's my ninja way! Believe it! I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way! I'll become the greatest ninja ever, and everyone will acknowledge my existence! I'll never give up, no matter what!",
      "It's over 9000! What, 9000? There's no way that can be right! Can it? The scouter must be broken! There's no way a Saiyan's power level could be that high! It's impossible! I've been training my whole life, and my power level is only 8000! How can a low-class warrior like Kakarot have a power level over 9000? This must be some kind of mistake! The scouter must be malfunctioning!",
      "Believe it! I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way! I'll become the greatest ninja ever, and everyone will acknowledge my existence! I'll never give up, no matter what! Even if I have to die, I'll never give up! That's my dream, that's my ninja way! I'll become the Hokage, and everyone will acknowledge my existence! Believe it!"
    ],
    aesop: [
      "The Hare was once boasting of his speed before the other animals. 'I have never yet been beaten,' said he, 'when I put forth my full speed. I challenge any one here to race with me.' The Tortoise said quietly, 'I accept your challenge.' 'That is a good joke,' said the Hare; 'I could dance round you all the way.' 'Keep your boasting till you've beaten,' answered the Tortoise. 'Shall we race?' So a course was fixed and a start was made. The Hare darted almost out of sight at once, but soon stopped and, to show his contempt for the Tortoise, lay down to have a nap. The Tortoise plodded on and plodded on, and when the Hare awoke from his nap, he saw the Tortoise just near the winning-post and could not run up in time to save the race.",
      "A Fox one day spied a beautiful bunch of ripe grapes hanging from a vine trained along the branches of a tree. The grapes seemed ready to burst with juice, and the Fox's mouth watered as he gazed longingly at them. The bunch hung from a high branch, and the Fox had to jump for it. The first time he jumped he missed it by a long way. So he walked off a short distance and took a running leap at it, only to fall short once more. Again and again he tried, but in vain. Now he sat down and looked at the grapes in disgust. 'What a fool I am,' he said. 'Here I am wearing myself out to get a bunch of sour grapes that are not worth gaping for.' And off he walked very, very scornfully.",
      "A Lion lay asleep in the forest, his great head resting on his paws. A timid little Mouse came upon him unexpectedly, and in her fright and haste to get away, ran across the Lion's nose. Roused from his nap, the Lion laid his huge paw angrily on the tiny creature to kill her. 'Spare me!' begged the poor Mouse. 'Please let me go and some day I will surely repay you.' The Lion was much amused to think that a Mouse could ever help him. But he was generous and finally let the Mouse go. Some days later, while stalking his prey in the forest, the Lion was caught in the toils of a hunter's net. Unable to free himself, he filled the forest with his angry roaring. The Mouse knew the voice and quickly found the Lion struggling in the net. Running to one of the great ropes that bound him, she gnawed it until it parted, and soon the Lion was free. 'You laughed when I said I would repay you,' said the Mouse. 'Now you see that even a Mouse can help a Lion.'"
    ]
  },
  medium: {
    shakespeare: [
      "To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take Arms against a Sea of troubles, And by opposing end them: to die, to sleep No more; and by a sleep, to say we end The heart-ache, and the thousand natural shocks That Flesh is heir to? 'Tis a consummation Devoutly to be wished. To die, to sleep, To sleep, perchance to Dream; aye, there's the rub, For in that sleep of death, what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There's the respect That makes Calamity of so long life: For who would bear the Whips and Scorns of time, The Oppressor's wrong, the proud man's Contumely, The pangs of despised Love, the Law's delay, The insolence of Office, and the Spurns That patient merit of the unworthy takes, When he himself might his Quietus make With a bare Bodkin? Who would Fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered Country, from whose bourn No Traveller returns, Puzzles the will, And makes us rather bear those ills we have, Than fly to others that we know not of.",
      "All the world's a stage, And all the men and women merely players; They have their exits and their entrances; And one man in his time plays many parts, His acts being seven ages. At first, the infant, Mewling and puking in the nurse's arms. Then the whining schoolboy, with his satchel And shining morning face, creeping like snail Unwillingly to school. And then the lover, Sighing like furnace, with a woeful ballad Made to his mistress' eyebrow. Then a soldier, Full of strange oaths and bearded like the pard, Jealous in honour, sudden and quick in quarrel, Seeking the bubble reputation Even in the cannon's mouth. And then the justice, In fair round belly with good capon lined, With eyes severe and beard of formal cut, Full of wise saws and modern instances; And so he plays his part. The sixth age shifts Into the lean and slippered pantaloon, With spectacles on nose and pouch on side; His youthful hose, well saved, a world too wide For his shrunk shank; and his big manly voice, Turning again toward childish treble, pipes And whistles in his sound. Last scene of all, That ends this strange eventful history, Is second childishness and mere oblivion, Sans teeth, sans eyes, sans taste, sans everything.",
      "The course of true love never did run smooth. But, either it was different in blood, Or else misgraffed in respect of years, Or else it stood upon the choice of friends, Or, if there were a sympathy in choice, War, death, or sickness did lay siege to it, Making it momentany as a sound, Swift as a shadow, short as any dream, Brief as the lightning in the collied night, That, in a spleen, unfolds both heaven and earth, And ere a man hath power to say 'Behold!' The jaws of darkness do devour it up: So quick bright things come to confusion. If then true lovers have been ever crossed, It stands as an edict in destiny: Then let us teach our trial patience, Because it is a customary cross, As due to love as thoughts and dreams and sighs, Wishes and tears, poor fancy's followers."
    ],
    anime: [
      "I am going to be the Hokage! No one will ever stop me! Even if I have to die, I'll never give up! I'll become the greatest ninja ever, and everyone will acknowledge my existence! That's my dream, that's my ninja way! Believe it! I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way! I'll become the greatest ninja ever, and everyone will acknowledge my existence! I'll never give up, no matter what! Even if I have to die, I'll never give up! That's my dream, that's my ninja way! I'll become the Hokage, and everyone will acknowledge my existence! Believe it! I'll never give up on my dream, no matter what! I'll become the greatest ninja ever, and everyone will acknowledge my existence! That's my nindo: my ninja way!",
      "It's over 9000! What, 9000? There's no way that can be right! Can it? The scouter must be broken! There's no way a Saiyan's power level could be that high! It's impossible! I've been training my whole life, and my power level is only 8000! How can a low-class warrior like Kakarot have a power level over 9000? This must be some kind of mistake! The scouter must be malfunctioning! There's no way a Saiyan's power level could be that high! It's impossible! I've been training my whole life, and my power level is only 8000! How can a low-class warrior like Kakarot have a power level over 9000? This must be some kind of mistake! The scouter must be malfunctioning!",
      "Believe it! I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way! I'll become the greatest ninja ever, and everyone will acknowledge my existence! I'll never give up, no matter what! Even if I have to die, I'll never give up! That's my dream, that's my ninja way! I'll become the Hokage, and everyone will acknowledge my existence! Believe it! I'll never give up on my dream, no matter what! I'll become the greatest ninja ever, and everyone will acknowledge my existence! That's my nindo: my ninja way! I'll never give up, no matter what! Even if I have to die, I'll never give up! That's my dream, that's my ninja way!"
    ],
    aesop: [
      "The Hare was once boasting of his speed before the other animals. 'I have never yet been beaten,' said he, 'when I put forth my full speed. I challenge any one here to race with me.' The Tortoise said quietly, 'I accept your challenge.' 'That is a good joke,' said the Hare; 'I could dance round you all the way.' 'Keep your boasting till you've beaten,' answered the Tortoise. 'Shall we race?' So a course was fixed and a start was made. The Hare darted almost out of sight at once, but soon stopped and, to show his contempt for the Tortoise, lay down to have a nap. The Tortoise plodded on and plodded on, and when the Hare awoke from his nap, he saw the Tortoise just near the winning-post and could not run up in time to save the race. Then said the Tortoise: 'Plodding wins the race.' The Hare was much mortified; and the Tortoise, plodding on, overtook him and soon passed the place where the Hare was sleeping. But the Hare slept on very peacefully; and when at last he did wake up, the Tortoise was near the goal. The Hare now ran his swiftest, but he could not overtake the Tortoise in time. The race is not always to the swift.",
      "A Fox one day spied a beautiful bunch of ripe grapes hanging from a vine trained along the branches of a tree. The grapes seemed ready to burst with juice, and the Fox's mouth watered as he gazed longingly at them. The bunch hung from a high branch, and the Fox had to jump for it. The first time he jumped he missed it by a long way. So he walked off a short distance and took a running leap at it, only to fall short once more. Again and again he tried, but in vain. Now he sat down and looked at the grapes in disgust. 'What a fool I am,' he said. 'Here I am wearing myself out to get a bunch of sour grapes that are not worth gaping for.' And off he walked very, very scornfully. The grapes were probably sour anyway. It's easy to despise what you cannot get. The Fox tried in vain to reach the grapes, and at last gave up, saying that they were probably sour anyway. It's easy to despise what you cannot get. The grapes were probably sour anyway. It's easy to despise what you cannot get.",
      "A Lion lay asleep in the forest, his great head resting on his paws. A timid little Mouse came upon him unexpectedly, and in her fright and haste to get away, ran across the Lion's nose. Roused from his nap, the Lion laid his huge paw angrily on the tiny creature to kill her. 'Spare me!' begged the poor Mouse. 'Please let me go and some day I will surely repay you.' The Lion was much amused to think that a Mouse could ever help him. But he was generous and finally let the Mouse go. Some days later, while stalking his prey in the forest, the Lion was caught in the toils of a hunter's net. Unable to free himself, he filled the forest with his angry roaring. The Mouse knew the voice and quickly found the Lion struggling in the net. Running to one of the great ropes that bound him, she gnawed it until it parted, and soon the Lion was free. 'You laughed when I said I would repay you,' said the Mouse. 'Now you see that even a Mouse can help a Lion.' A kindness is never wasted. The Lion was much amused to think that a Mouse could ever help him. But he was generous and finally let the Mouse go. Some days later, while stalking his prey in the forest, the Lion was caught in the toils of a hunter's net."
    ]
  },
  long: {
    shakespeare: [
      "To be, or not to be, that is the question: Whether 'tis nobler in the mind to suffer The slings and arrows of outrageous fortune, Or to take Arms against a Sea of troubles, And by opposing end them: to die, to sleep No more; and by a sleep, to say we end The heart-ache, and the thousand natural shocks That Flesh is heir to? 'Tis a consummation Devoutly to be wished. To die, to sleep, To sleep, perchance to Dream; aye, there's the rub, For in that sleep of death, what dreams may come, When we have shuffled off this mortal coil, Must give us pause. There's the respect That makes Calamity of so long life: For who would bear the Whips and Scorns of time, The Oppressor's wrong, the proud man's Contumely, The pangs of despised Love, the Law's delay, The insolence of Office, and the Spurns That patient merit of the unworthy takes, When he himself might his Quietus make With a bare Bodkin? Who would Fardels bear, To grunt and sweat under a weary life, But that the dread of something after death, The undiscovered Country, from whose bourn No Traveller returns, Puzzles the will, And makes us rather bear those ills we have, Than fly to others that we know not of. Thus Conscience does make Cowards of us all, And thus the Native hue of Resolution Is sicklied o'er, with the pale cast of Thought, And enterprises of great pitch and moment, With this regard their Currents turn awry, And lose the name of Action. Soft you now, The fair Ophelia? Nymph, in thy Orisons Be all my sins remembered.",
      "All the world's a stage, And all the men and women merely players; They have their exits and their entrances; And one man in his time plays many parts, His acts being seven ages. At first, the infant, Mewling and puking in the nurse's arms. Then the whining schoolboy, with his satchel And shining morning face, creeping like snail Unwillingly to school. And then the lover, Sighing like furnace, with a woeful ballad Made to his mistress' eyebrow. Then a soldier, Full of strange oaths and bearded like the pard, Jealous in honour, sudden and quick in quarrel, Seeking the bubble reputation Even in the cannon's mouth. And then the justice, In fair round belly with good capon lined, With eyes severe and beard of formal cut, Full of wise saws and modern instances; And so he plays his part. The sixth age shifts Into the lean and slippered pantaloon, With spectacles on nose and pouch on side; His youthful hose, well saved, a world too wide For his shrunk shank; and his big manly voice, Turning again toward childish treble, pipes And whistles in his sound. Last scene of all, That ends this strange eventful history, Is second childishness and mere oblivion, Sans teeth, sans eyes, sans taste, sans everything. The world is a stage, and all the men and women merely players. They have their exits and their entrances, and one man in his time plays many parts. His acts being seven ages. At first, the infant, mewling and puking in the nurse's arms. Then the whining schoolboy, with his satchel and shining morning face, creeping like snail unwillingly to school.",
      "The course of true love never did run smooth. But, either it was different in blood, Or else misgraffed in respect of years, Or else it stood upon the choice of friends, Or, if there were a sympathy in choice, War, death, or sickness did lay siege to it, Making it momentany as a sound, Swift as a shadow, short as any dream, Brief as the lightning in the collied night, That, in a spleen, unfolds both heaven and earth, And ere a man hath power to say 'Behold!' The jaws of darkness do devour it up: So quick bright things come to confusion. If then true lovers have been ever crossed, It stands as an edict in destiny: Then let us teach our trial patience, Because it is a customary cross, As due to love as thoughts and dreams and sighs, Wishes and tears, poor fancy's followers. The course of true love never did run smooth. But, either it was different in blood, Or else misgraffed in respect of years, Or else it stood upon the choice of friends, Or, if there were a sympathy in choice, War, death, or sickness did lay siege to it, Making it momentany as a sound, Swift as a shadow, short as any dream, Brief as the lightning in the collied night, That, in a spleen, unfolds both heaven and earth, And ere a man hath power to say 'Behold!' The jaws of darkness do devour it up: So quick bright things come to confusion."
    ],
    anime: [
      "I am going to be the Hokage! No one will ever stop me! Even if I have to die, I'll never give up! I'll become the greatest ninja ever, and everyone will acknowledge my existence! That's my dream, that's my ninja way! Believe it! I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way! I'll become the greatest ninja ever, and everyone will acknowledge my existence! I'll never give up, no matter what! Even if I have to die, I'll never give up! That's my dream, that's my ninja way! I'll become the Hokage, and everyone will acknowledge my existence! Believe it! I'll never give up on my dream, no matter what! I'll become the greatest ninja ever, and everyone will acknowledge my existence! That's my nindo: my ninja way! I'll never give up, no matter what! Even if I have to die, I'll never give up! That's my dream, that's my ninja way! I'll become the Hokage, and everyone will acknowledge my existence! Believe it! I'll never give up on my dream, no matter what! I'll become the greatest ninja ever, and everyone will acknowledge my existence! That's my nindo: my ninja way!",
      "It's over 9000! What, 9000? There's no way that can be right! Can it? The scouter must be broken! There's no way a Saiyan's power level could be that high! It's impossible! I've been training my whole life, and my power level is only 8000! How can a low-class warrior like Kakarot have a power level over 9000? This must be some kind of mistake! The scouter must be malfunctioning! There's no way a Saiyan's power level could be that high! It's impossible! I've been training my whole life, and my power level is only 8000! How can a low-class warrior like Kakarot have a power level over 9000? This must be some kind of mistake! The scouter must be malfunctioning! There's no way a Saiyan's power level could be that high! It's impossible! I've been training my whole life, and my power level is only 8000! How can a low-class warrior like Kakarot have a power level over 9000? This must be some kind of mistake! The scouter must be malfunctioning! There's no way a Saiyan's power level could be that high! It's impossible! I've been training my whole life, and my power level is only 8000! How can a low-class warrior like Kakarot have a power level over 9000? This must be some kind of mistake! The scouter must be malfunctioning!",
      "Believe it! I'm not gonna run away, I never go back on my word! That's my nindo: my ninja way! I'll become the greatest ninja ever, and everyone will acknowledge my existence! I'll never give up, no matter what! Even if I have to die, I'll never give up! That's my dream, that's my ninja way! I'll become the Hokage, and everyone will acknowledge my existence! Believe it! I'll never give up on my dream, no matter what! I'll become the greatest ninja ever, and everyone will acknowledge my existence! That's my nindo: my ninja way! I'll never give up, no matter what! Even if I have to die, I'll never give up! That's my dream, that's my ninja way! I'll become the Hokage, and everyone will acknowledge my existence! Believe it! I'll never give up on my dream, no matter what! I'll become the greatest ninja ever, and everyone will acknowledge my existence! That's my nindo: my ninja way! I'll never give up, no matter what! Even if I have to die, I'll never give up! That's my dream, that's my ninja way!"
    ],
    aesop: [
      "The Hare was once boasting of his speed before the other animals. 'I have never yet been beaten,' said he, 'when I put forth my full speed. I challenge any one here to race with me.' The Tortoise said quietly, 'I accept your challenge.' 'That is a good joke,' said the Hare; 'I could dance round you all the way.' 'Keep your boasting till you've beaten,' answered the Tortoise. 'Shall we race?' So a course was fixed and a start was made. The Hare darted almost out of sight at once, but soon stopped and, to show his contempt for the Tortoise, lay down to have a nap. The Tortoise plodded on and plodded on, and when the Hare awoke from his nap, he saw the Tortoise just near the winning-post and could not run up in time to save the race. Then said the Tortoise: 'Plodding wins the race.' The Hare was much mortified; and the Tortoise, plodding on, overtook him and soon passed the place where the Hare was sleeping. But the Hare slept on very peacefully; and when at last he did wake up, the Tortoise was near the goal. The Hare now ran his swiftest, but he could not overtake the Tortoise in time. The race is not always to the swift. The Hare was once boasting of his speed before the other animals. 'I have never yet been beaten,' said he, 'when I put forth my full speed. I challenge any one here to race with me.' The Tortoise said quietly, 'I accept your challenge.' 'That is a good joke,' said the Hare; 'I could dance round you all the way.' 'Keep your boasting till you've beaten,' answered the Tortoise. 'Shall we race?'",
      "A Fox one day spied a beautiful bunch of ripe grapes hanging from a vine trained along the branches of a tree. The grapes seemed ready to burst with juice, and the Fox's mouth watered as he gazed longingly at them. The bunch hung from a high branch, and the Fox had to jump for it. The first time he jumped he missed it by a long way. So he walked off a short distance and took a running leap at it, only to fall short once more. Again and again he tried, but in vain. Now he sat down and looked at the grapes in disgust. 'What a fool I am,' he said. 'Here I am wearing myself out to get a bunch of sour grapes that are not worth gaping for.' And off he walked very, very scornfully. The grapes were probably sour anyway. It's easy to despise what you cannot get. The Fox tried in vain to reach the grapes, and at last gave up, saying that they were probably sour anyway. It's easy to despise what you cannot get. The grapes were probably sour anyway. It's easy to despise what you cannot get. The Fox tried in vain to reach the grapes, and at last gave up, saying that they were probably sour anyway. It's easy to despise what you cannot get. The grapes were probably sour anyway. It's easy to despise what you cannot get.",
      "A Lion lay asleep in the forest, his great head resting on his paws. A timid little Mouse came upon him unexpectedly, and in her fright and haste to get away, ran across the Lion's nose. Roused from his nap, the Lion laid his huge paw angrily on the tiny creature to kill her. 'Spare me!' begged the poor Mouse. 'Please let me go and some day I will surely repay you.' The Lion was much amused to think that a Mouse could ever help him. But he was generous and finally let the Mouse go. Some days later, while stalking his prey in the forest, the Lion was caught in the toils of a hunter's net. Unable to free himself, he filled the forest with his angry roaring. The Mouse knew the voice and quickly found the Lion struggling in the net. Running to one of the great ropes that bound him, she gnawed it until it parted, and soon the Lion was free. 'You laughed when I said I would repay you,' said the Mouse. 'Now you see that even a Mouse can help a Lion.' A kindness is never wasted. The Lion was much amused to think that a Mouse could ever help him. But he was generous and finally let the Mouse go. Some days later, while stalking his prey in the forest, the Lion was caught in the toils of a hunter's net. Unable to free himself, he filled the forest with his angry roaring. The Mouse knew the voice and quickly found the Lion struggling in the net. Running to one of the great ropes that bound him, she gnawed it until it parted, and soon the Lion was free. 'You laughed when I said I would repay you,' said the Mouse. 'Now you see that even a Mouse can help a Lion.' A kindness is never wasted."
    ]
  }
}; 